version: '3.8'

services:
  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "5108:5108"
    networks:
      - todo-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./todo-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge